[package]
name = "chess-nn-2"
version = "0.0.0"
edition = "2024"
authors = ["dmyTRUEk"]

[profile.release]
opt-level = 3
#lto = "fat"
lto = "thin"
codegen-units = 1
panic = "abort"
strip = "debuginfo"
#target-cpu = "native" -> RUSTFLAGS='-C target-cpu=native'

[dependencies]
# chess = { git = "https://github.com/jordanbray/chess", rev = "80e73cd93b3ca5dd4dc952c77355e37a5bb61b30" }
chess = "3.2.0"
chrono = "0.4.44"
itertools = "0.14.0"
nalgebra = "0.34.2"
num_enum = "0.7.6"
rand = "0.10.1"
rayon = "1.12.0"
